### ISSUE TITLE
Command fails to start kubelet

### ISSUE THREAD

**Issue by celestialorb** [gavinzhou/ci-minikube#2]
https://github.com/gavinzhou/ci-minikube/blob/39f775bcced1495e5244738cf1f7b948ac739abb/.circleci/config.yml#L35

While working on a CI workflow using Minikube myself I was unable to get my equivalent of this command to run successfully. It errors out with:

```
E0204 10:50:46.985278     134 start.go:302] Error updating cluster:  starting kubelet: running command: 

sudo systemctl daemon-reload &&

sudo systemctl enable kubelet &&

sudo systemctl start kubelet

: exit status 1
```
After debugging the job over SSH I believe it is because I cannot seem to access `systemctl` in CircleCI, even as the root user. Are you seeing this behavior as well?

**Comment by csandanov** [comment]
you probably missed `image: circleci/classic:201808-01` in your config

**Comment by celestialorb** [comment]
Closing this as it's old.
